/* 
* Copyright (C) 2002-2011 XimpleWare, info@ximpleware.com
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 3/2/2010 7:22:50 PM
//----------------------------------------------------

namespace com.ximpleware.xpath
 {

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public const int AXISNAME = 33;
  public const int MOD = 22;
  public const int LB = 10;
  public const int EOF = 0;
  public const int MULT = 18;
  public const int NUMBER = 28;
  public const int RP = 9;
  public const int LP = 8;
  public const int LT = 13;
  public const int SUB = 3;
  public const int AT = 6;
  public const int OR = 24;
  public const int DIV = 21;
  public const int GT = 12;
  public const int FNAME = 30;
  public const int NTEST = 31;
  public const int SLASH = 19;
  public const int ADD = 2;
  public const int LE = 15;
  public const int NE = 17;
  public const int NAME = 32;
  public const int AND = 23;
  public const int LITERAL = 29;
  public const int GE = 14;
  public const int DOT = 4;
  public const int DDOT = 5;
  public const int DOLLAR = 27;
  public const int DSLASH = 20;
  public const int UMINUS = 26;
  public const int UNION = 25;
  public const int EQ = 16;
  public const int COMMA = 7;
  public const int error = 1;
  public const int RB = 11;
	}
}
