
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 4/17/2006 6:36:39 PM
//----------------------------------------------------

namespace com.ximpleware.xpath
 {

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public const int DOLLAR = 27;
  public const int GE = 14;
  public const int SLASH = 19;
  public const int COMMA = 7;
  public const int NTEST = 31;
  public const int DIV = 21;
  public const int DOT = 4;
  public const int UMINUS = 26;
  public const int NAME = 32;
  public const int DSLASH = 20;
  public const int EOF = 0;
  public const int LT = 13;
  public const int OR = 24;
  public const int ADD = 2;
  public const int AXISNAME = 33;
  public const int AT = 6;
  public const int AND = 23;
  public const int FNAME = 30;
  public const int DDOT = 5;
  public const int LE = 15;
  public const int LITERAL = 29;
  public const int MULT = 18;
  public const int SUB = 3;
  public const int EQ = 16;
  public const int LP = 8;
  public const int NUMBER = 28;
  public const int RB = 11;
  public const int GT = 12;
  public const int LB = 10;
  public const int MOD = 22;
  public const int RP = 9;
  public const int error = 1;
  public const int UNION = 25;
  public const int NE = 17;
	}
}
